
COLOR_BLACK:    0, 0, 0
COLOR_WHITE:    0, 0, 0
COLOR_GRAY:     128, 128, 128
COLOR_RED:      255, 0, 0
COLOR_GREEN:    0, 255, 0
COLOR_BLUE:     0, 0, 255
COLOR_PURPLE:   255, 0, 255
COLOR_YELLOW:   0, 255, 255
COLOR_ORANGE:   255, 255, 0

sun:

    speed: 1

    S_CENTER_COLOR: 255, 223, 147
    S_HALF_COLOR: 252, 217, 133
    S_EDGE_COLOR: 255, 180, 0
    S_COLORS: S_CENTER_COLOR, S_HALF_COLOR, S_HALF_COLOR, S_HALF_COLOR, S_EDGE_COLOR

    R_START_COLOR: 255, 180, 0
    R_END_COLOR: COLOR_BLACK
    R_COLORS: R_START_COLOR, R_END_COLOR
